name: env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - brotlipy=0.7.0=py39h27cfd23_1003
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda=23.1.0=py39h06a4308_0
  - conda-content-trust=0.1.3=py39h06a4308_0
  - conda-package-handling=2.0.2=py39h06a4308_0
  - conda-package-streaming=0.7.0=py39h06a4308_0
  - cryptography=38.0.4=py39h9ce1e76_0
  - idna=3.4=py39h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.3.1=py39h06a4308_0
  - pluggy=1.0.0=py39h06a4308_1
  - pycosat=0.6.4=py39h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.16=h7a1cb2a_0
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py39h06a4308_0
  - ruamel.yaml=0.17.21=py39h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py39h5eee18b_1
  - setuptools=65.6.3=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.1=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=py39h06a4308_0
  - tqdm=4.64.1=py39h06a4308_0
  - urllib3=1.26.14=py39h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - zstandard=0.18.0=py39h5eee18b_0
  - pip:
      - absl-py==1.4.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - anyio==4.0.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.4.0
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - babel==2.12.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - cachetools==5.3.1
      - click==8.1.7
      - cmake==3.27.4.1
      - comm==0.1.4
      - contourpy==1.1.0
      - cycler==0.11.0
      - debugpy==1.7.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - exceptiongroup==1.1.3
      - executing==1.2.0
      - fastjsonschema==2.18.0
      - filelock==3.12.3
      - fonttools==4.42.1
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.9.0
      - gitdb==4.0.10
      - gitpython==3.1.35
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.58.0
      - huggingface-hub==0.16.4
      - hydra-core==1.3.2
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.1
      - ipykernel==6.25.2
      - ipython==8.15.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.0
      - isoduration==20.11.0
      - jedi==0.19.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - jupyter-client==8.3.1
      - jupyter-console==6.6.3
      - jupyter-core==5.3.1
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.3
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.5
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.24.0
      - jupyterlab-widgets==3.0.8
      - kiwisolver==1.4.5
      - lightgbm==4.1.0
      - lit==16.0.6
      - markdown==3.4.4
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - mistune==3.0.1
      - mpmath==1.3.0
      - multidict==6.0.4
      - nbclient==0.8.0
      - nbconvert==7.8.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.7
      - networkx==3.1
      - notebook==7.0.3
      - notebook-shim==0.2.3
      - numpy==1.25.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - overrides==7.4.0
      - packaging==23.1
      - pandas==1.4.4
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.0
      - platformdirs==3.10.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - protobuf==3.20.1
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==13.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydeprecate==0.3.2
      - pygments==2.16.1
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytorch-lifestream==0.5.2
      - pytorch-lightning==1.6.5
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.4.4
      - qtpy==2.4.0
      - referencing==0.30.2
      - regex==2023.8.8
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.10.2
      - rsa==4.9
      - ruptures==1.1.8
      - safetensors==0.3.3
      - scikit-learn==1.3.0
      - scipy==1.11.2
      - seaborn==0.12.2
      - send2trash==1.8.2
      - sentry-sdk==1.30.0
      - setproctitle==1.3.2
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.2
      - sympy==1.12
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.1
      - terminado==0.17.1
      - threadpoolctl==3.2.0
      - tinycss2==1.2.1
      - tokenizers==0.13.3
      - tomli==2.0.1
      - torch==2.0.1
      - torchmetrics==1.0.2
      - torchvision==0.15.2
      - tornado==6.3.3
      - traitlets==5.9.0
      - transformers==4.33.1
      - triton==2.0.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - uri-template==1.3.0
      - wandb==0.15.10
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.3
      - werkzeug==2.3.7
      - widgetsnbextension==4.0.8
      - yarl==1.9.2
      - zipp==3.16.2
