transforms:
 - 
    _target_: src.preprocessing.ToType
    target_type: float32
    col_name_original: amount
 - 
    _target_: src.preprocessing.CustomDatetimeNormalization
    col_name_original: timestamp
 - 
    _target_: ptls.preprocessing.PandasDataPreprocessor
    col_id: user_id
    col_event_time: timestamp
    event_time_transformation: none
    cols_first_item: [global_target]
    cols_category: [mcc_code]
    cols_numerical: [amount]
    return_records: False

source: data/preprocessed_new/churn.parquet
cache_dir: cache
val_size: .1
test_size: .1
random_state: 42
