transforms:
 - 
    _target_: src.preprocessing.ToType
    target_type: float32
    col_name_original: amount
 -
    _target_: ptls.preprocessing.pandas.category_identity_encoder.CategoryIdentityEncoder
    col_name_original: default_target
    col_name_target: local_target
 - 
    _target_: ptls.preprocessing.PandasDataPreprocessor
    col_id: user_id
    col_event_time: timestamp
    event_time_transformation: dt_to_timestamp
    cols_category: [mcc_code]
    cols_numerical: [amount]
    cols_first_item: [global_target]
    return_records: False

source: data/preprocessed_new/default.parquet
cache_dir: cache
val_size: .1
test_size: .1
random_state: 42