_target_: ptls.nn.RnnSeqEncoder
trx_encoder:
  _target_: ptls.nn.TrxEncoder
  use_batch_norm_with_lens: True
  norm_embeddings: False
  embeddings_noise: 0.0003
  embeddings: 
    mcc_code:   
      in: 345
      out: 24
  numeric_values: {amount: log}
hidden_size: 1024
bidir: False
trainable_starter: static
type: lstm
is_reduce_sequence: True
