_target_: ptls.nn.RnnSeqEncoder
trx_encoder:
  _target_: ptls.nn.TrxEncoder
  use_batch_norm_with_lens: True
  norm_embeddings: False
  embeddings_noise: 0.003
  embeddings: {mcc_code: {in: 345, out: 16}}
  out_of_index: clip
  numeric_values: {
    amount: identity
  }
hidden_size: 800
bidir: False
trainable_starter: static
type: gru