_target_: src.nn.CoticSeqEncoder
trx_encoder: null # no trx encoder for COTIC
is_reduce_sequence: False
input_size: 24 # default params from the COTIC paper
hidden_size: 16
num_types: 100
kernel:
  _target_: src.nn.cotic_components.Kernel
  hidden1: 8
  hidden2: 4
  hidden3: 8
  in_channels: ${backbone.encoder.hidden_size}
  out_channels: ${backbone.encoder.hidden_size}
num_layers: 9
kernel_size: 5
reducer: maxpool